### ISSUE TITLE
Maintenance: tags+links

### ISSUE THREAD

**Issue by webknjaz** [webknjaz/pip-with-requires-python#3]
@graingert could you push the tags for older releases published to https://pypi.org/project/pip-with-requires-python/#history? It'd be good if there was a matching commit.

Also, mind linking PyPI via the URL field in the repo?

P.S. I assume `0.0.0a0` is nonfunctional? How about marking it as `yanked`?

**Comment by graingert** [comment]
@webknjaz hello, v1.0.0 tagged and 0.0.0a0 yanked

**Comment by graingert** [comment]
sorry for the delay I didn't get a notification :(
